<?php

/**
 * @file
 * Bastides module for the RESTful module.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function bastides_module_ctools_plugin_directory($module, $plugin) {
  if ($module == 'restful') {
    return 'plugins/' . $plugin;
  }
}


/**
 * Implements hook_action_info
 * @return array associative array of action descriptions
 */
function bastides_module_action_info() {
  return array(
    'bastides_module_get_location' => array(
      'type' => 'node',
      'label' => t('Look up village lat,lon from city name with api.geonames.org'),
      'behavior' => array('changes_property'),
      'configurable' => FALSE,
      'vbo_configurable' => FALSE,
      'triggers' => array('any'),
    ),
    'bastides_module_get_location_google' => array(
      'type' => 'node',
      'label' => t('Look up village lat,lon from city name with maps.googleapis.com'),
      'behavior' => array('changes_property'),
      'configurable' => FALSE,
      'vbo_configurable' => TRUE,
      'triggers' => array('any'),
    ),
  );
}

function bastides_module_get_location(&$node, $context) {
  $wrapper = entity_metadata_wrapper('node', $node);
  if ($wrapper->type->value() == 'village_metadata') {
    $village = urlencode($wrapper->field_village_name->value());
    $request = "http://api.geonames.org/search?name_equals=$village&country=FR&username=jgreidy";
    $raw = file_get_contents($request);
    if ($raw === FALSE) return;
    $p = xml_parser_create();
    $ok = xml_parse_into_struct($p, $raw, $vals, $index);
    xml_parser_free($p);
    if ($ok != 1) return;
    if (empty($index['LAT'][0]) || empty($index['LNG'][0])) return;
    $lat_index = $index['LAT'][0];
    $lon_index = $index['LNG'][0];
    $data = array(
      'lat' => $vals["$lat_index"]['value'],
      'lon' => $vals["$lon_index"]['value'],
    );
    $wrapper->field_village_location->set($data);
  }
}

function bastides_module_get_location_google(&$node, $context) {
  $wrapper = entity_metadata_wrapper('node', $node);
  if ($wrapper->type->value() == 'village_metadata') {
    $village = urlencode($wrapper->field_village_name->value());
    $api_key = !empty($options['bastides_module_google_api_key']) ? $options['bastides_module_google_api_key'] : '';
    $request = "https://maps.googleapis.com/maps/api/geocode/json?address=$village&components=city:FR&key=$api_key";
    $raw = file_get_contents($request);
    if ($raw === FALSE) return;
    dsm($raw);
    $goods = json_decode($raw);
    dsm($goods);
    return;
    // $data = array(
    //   'lat' => $vals["$lat_index"]['value'],
    //   'lon' => $vals["$lon_index"]['value'],
    // );
    // $wrapper->field_village_location->set($data);
  }
}

function bastides_module_get_location_google_form($options) {
  $form = array();
  $form['bastides_module_google_api_key'] = array(
    '#type' => 'textfield',
    '#title' => t('API key for maps.googleapis.com'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
    '#default_value' => !empty($options['bastides_module_google_api_key']) ? $options['bastides_module_google_api_key'] : '',
  );

  return $form;
}

function bastides_module_get_bastides_module_form($settings, &$form_state) {
  $form = bastides_module_get_location_google_form($settings['settings']);
  return $form;
}

function bastides_module_get_location_google_submit($form, $form_state) {
  $return = array();
  $return['bastides_module_google_api_key'] = $form_state['values']['bastides_module_google_api_key'];
  return $return;
}
